/*=========================================================
Object Name : DDL_ETL_RECONCILIATION_LOG
Purpose     : Pipeline audit and reconciliation log for all ETL executions
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
    LOG_ID                  NUMBER          AUTOINCREMENT PRIMARY KEY,
    BATCH_ID                VARCHAR(100)    NOT NULL,
    PROCEDURE_NAME          VARCHAR(255),
    LOAD_TYPE               VARCHAR(50),
    STATUS                  VARCHAR(50),
    WATERMARK_FROM          TIMESTAMP_NTZ,
    WATERMARK_TO            TIMESTAMP_NTZ,
    SOURCE_COUNT            NUMBER(18,0),
    INSERTED_COUNT          NUMBER(18,0),
    UPDATED_COUNT           NUMBER(18,0),
    DELETED_COUNT           NUMBER(18,0),
    EXCLUDED_COUNT          NUMBER(18,0),
    ERROR_MESSAGE           VARCHAR(4000),
    START_TS                TIMESTAMP_NTZ,
    END_TS                  TIMESTAMP_NTZ,
    DURATION_SECONDS        NUMBER(18,4),
    CREATED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- SECTION 2: Constraints
-- PK defined inline above via AUTOINCREMENT PRIMARY KEY.
-- BATCH_ID is a unique run identifier generated per SP execution.

-- SECTION 3: Notes
-- LOAD_TYPE: FULL or INCREMENTAL.
-- STATUS: SUCCESS, FAILED, PARTIAL.
-- WATERMARK_FROM/TO capture the incremental window applied per run.
-- SLA target: 1M records processed within 300 seconds (5 minutes).