/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : SCD Type 1 analytics-ready target table for aerospace parts inventory
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

-- SECTION 1: Object Definition
CREATE OR REPLACE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (
    PART_NUMBER             VARCHAR(100)    NOT NULL,
    PART_NAME               VARCHAR(255),
    MANUFACTURER            VARCHAR(255),
    LIFECYCLE_STATUS        VARCHAR(100),
    CERTIFICATION_STATUS    VARCHAR(100),
    INSTALLATION_DATE       DATE,
    LEAD_TIME_DAYS          NUMBER(10,0),
    WEIGHT_KG               NUMBER(18,4),
    UNIT_PRICE_USD          NUMBER(18,4),
    STOCK_QUANTITY          NUMBER(10,0),
    WAREHOUSE_LOCATION      VARCHAR(255),
    SUPPLIER_ID             VARCHAR(100),
    CATEGORY                VARCHAR(100),
    RISK_SCORE              VARCHAR(50),
    IS_DELETED              BOOLEAN         DEFAULT FALSE,
    UPDATED_AT              TIMESTAMP_NTZ,
    CREATED_AT              TIMESTAMP_NTZ,
    ETL_LOAD_TS             TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    ETL_BATCH_ID            VARCHAR(100)
);

-- SECTION 2: Constraints
ALTER TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
    ADD CONSTRAINT PK_AEROSPACE_PARTS_TARGET PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- SCD Type 1: updates overwrite existing records; no history retained.
-- RISK_SCORE derived in SP: High/Medium/Low based on CERTIFICATION_STATUS + LEAD_TIME_DAYS.
-- IS_DELETED=TRUE indicates soft-deleted (Decommissioned) records absent from source.
-- ETL_BATCH_ID links to ETL_RECONCILIATION_LOG.BATCH_ID for traceability.