/*=========================================================
Object Name : QA_AEROSPACE_PARTS_PIPELINE
Purpose     : QA acceptance criteria queries AC-001 to AC-010
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- ── AC-001 : Row Count – Target must contain rows after load ──────────────────
-- PASS: target_count > 0
-- AC-001
SELECT
    'AC-001' AS CRITERIA,
    'Target Row Count > 0' AS DESCRIPTION,
    COUNT(*) AS TARGET_COUNT,
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

-- ── AC-002 : Deduplication – No duplicate PART_NUMBER in target ───────────────
-- PASS: zero rows returned
-- AC-002
SELECT
    'AC-002' AS CRITERIA,
    'No Duplicate PART_NUMBER' AS DESCRIPTION,
    PART_NUMBER,
    COUNT(*) AS CNT
FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
GROUP BY PART_