/*=========================================================
Object Name : SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : SCD Type 1 stored procedure for aerospace parts pipeline
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
    var db         = 'GEN_AI_POC_SNOWFLAKECOE';
    var schema     = 'SDLC_WIZARD';
    var src        = db + '.' + schema + '.AEROSPACE_PARTS_SOURCE';
    var tgt        = db + '.' + schema + '.AEROSPACE_PARTS_TARGET';
    var log        = db + '.' + schema + '.ETL_RECONCILIATION_LOG';
    var proc_name  = 'SP_LOAD_AEROSPACE_PARTS_SCD1';
    var start_ts   = new Date();
    var batch_id   = 'BATCH_' + start_ts.toISOString().replace(/[-:.TZ]/g,'').substring(0,17);
    var load_type  = 'INCREMENTAL';
    var wm_-- SECTION 2: Source Processing
from    = null, wm_to = null;
    var src_cnt    = 0, ins_cnt = 0, upd_cnt = 0, del_cnt = 0, exc_cnt = 0;
    var err_msg    = null;

    try {
        // Determine watermark
        var wm_sql = `SELECT MAX(WATERMARK_TO) FROM ${log} WHERE STATUS='SUCCESS' AND PROCEDURE_NAME='${proc_name}'`;
        var wm_res = snowflake.execute({sqlText: wm_sql});
        wm_res.next();
        var last_wm = wm_res.getColumnValue(1);
        -- SECTION 3: Data Validation
if (!last_wm) { load_type = 'FULL'; }
        wm_from = last_wm;

        // Watermark ceiling
        var now_res = snowflake.execute({sqlText: `SELECT CURRENT_TIMESTAMP()`});
        now_res.next();
        wm_to = now_res.getColumnValue(1);

        // Build incremental filter
        var wm_filter = load_type === 'FULL'
            ? '1=1'
            : `UPDATED_AT > '${wm_from}'`;

        // Source count (before exclusions)
        var sc_res = snowflake.execute({sqlText: `SELECT COUNT(*) FROM ${src} WHERE ${wm_filter}`});
        sc_res.next();
        src_cnt = sc_res.getColumnValue(1);

        // Exclusion count
        var exc_sql = `
            SELECT COUNT(*) FROM ${src}
            WHERE ${wm_filter}
              AND UPPER(LIFECYCLE_STATUS) = 'END OF LIFE'
              AND INSTALLATION_DATE < DATEADD('year', -3, CURRENT_DATE())`;
        var exc_res = snowflake.execute({sqlText: exc_sql});
        exc_res.next();
        exc_cnt = exc_res.getColumnValue(1);

        // Deduplicated + transformed staging CTE + MERGE
        var merge_sql = `
        -- SECTION 4: Merge Logic
MERGE INTO ${tgt} AS T
        USING (
            WITH DEDUPED AS (
                SELECT *,
                       ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS RN
                FROM ${src}
                WHERE ${wm_filter}
                  AND NOT (UPPER(LIFECYCLE_STATUS) = 'END OF LIFE'
                           AND INSTALLATION_DATE < DATEADD('year', -3, CURRENT_DATE()))
            ),
            TRANSFORMED AS (
                SELECT
                    PART_NUMBER,
                    PART_NAME,
                    INITCAP(MANUFACTURER)                                   AS MANUFACTURER,
                    LIFECYCLE_STATUS,
                    CERTIFICATION_STATUS,
                    INSTALLATION_DATE,
                    LEAD_TIME_DAYS,
                    CASE WHEN WEIGHT_KG <= 0 THEN NULL ELSE WEIGHT_KG END   AS WEIGHT_KG,
                    ROUND(UNIT_PRICE_USD, 2)                                AS UNIT_PRICE_USD,
                    STOCK_QUANTITY,
                    WAREHOUSE_LOCATION,
                    SUPPLIER_ID,
                    CATEGORY,
                    UPDATED_AT,
                    CREATED_AT,
                    CASE
                        WHEN UPPER(CERTIFICATION_STATUS) = 'PENDING' AND LEAD_TIME_DAYS > 90  THEN 'High Risk'
                        WHEN UPPER(CERTIFICATION_STATUS) = 'PENDING' OR  LEAD_TIME_DAYS > 120 THEN 'Medium Risk'
                        WHEN UPPER(CERTIFICATION_STATUS) IN ('FAA','EASA','DUAL') AND LEAD_TIME_DAYS <= 60 THEN 'Low Risk'
                        ELSE 'Medium Risk'
                    END AS RISK_SCORE
                FROM DEDUPED WHERE RN = 1
            )
            SELECT * FROM TRANSFORMED
        ) AS S ON T.PART_NUMBER = S.PART_NUMBER
        WHEN MATCHED THEN UPDATE SET
            T.PART_NAME          = S.PART_NAME,
            T.MANUFACTURER       = S.MANUFACTURER,
            T.LIFECYCLE_STATUS   = S.LIFECYCLE_STATUS,
            T.CERTIFICATION_STATUS = S.CERTIFICATION_STATUS,
            T.INSTALLATION_DATE  = S.INSTALLATION_DATE,
            T.LEAD_TIME_DAYS     = S.LEAD_TIME_DAYS,
            T.WEIGHT_KG          = S.WEIGHT_KG,
            T.UNIT_PRICE_USD     = S.UNIT_PRICE_USD,
            T.STOCK_QUANTITY     = S.STOCK_QUANTITY,
            T.WAREHOUSE_LOCATION = S.WAREHOUSE_LOCATION,
            T.SUPPLIER_ID        = S.SUPPLIER_ID,
            T.CATEGORY           = S.CATEGORY,
            T.RISK_SCORE         = S.RISK_SCORE,
            T.UPDATED_AT         = S.UPDATED_AT,
            T.IS_DELETED         = FALSE,
            T.ETL_LOAD_TS        = CURRENT_TIMESTAMP(),
            T.ETL_BATCH_ID       = '${batch_id}'
        WHEN NOT MATCHED THEN INSERT (
            PART_NUMBER, PART_NAME, MANUFACTURER, LIFECYCLE_STATUS, CERTIFICATION_STATUS,
            INSTALLATION_DATE, LEAD_TIME_DAYS, WEIGHT_KG, UNIT_PRICE_USD, STOCK_QUANTITY,
            WAREHOUSE_LOCATION, SUPPLIER_ID, CATEGORY, RISK_SCORE, IS_DELETED,
            UPDATED_AT, CREATED_AT, ETL_LOAD_TS, ETL_BATCH_ID
        ) VALUES (
            S.PART_NUMBER, S.PART_NAME, S.MANUFACTURER, S.LIFECYCLE_STATUS, S.CERTIFICATION_STATUS,
            S.INSTALLATION_DATE, S.LEAD_TIME_DAYS, S.WEIGHT_KG, S.UNIT_PRICE_USD, S.STOCK_QUANTITY,
            S.WAREHOUSE_LOCATION, S.SUPPLIER_ID, S.CATEGORY, S.RISK_SCORE, FALSE,
            S.UPDATED_AT, S.CREATED_AT, CURRENT_TIMESTAMP(), '${batch_id}'
        )`;

        var merge_res = snowflake.execute({sqlText: merge_sql});
        merge_res.next();
        var rows_ins = merge_res.getColumnValue(1);
        var rows_upd = merge_res.getColumnValue(2);
        ins_cnt = rows_ins;
        upd_cnt = rows_upd;

        // Soft delete: mark records not in current source window as Decommissioned
        var soft_del_sql = `
        UPDATE ${tgt} T
        SET T.LIFECYCLE_STATUS = 'Decommissioned',
            T.IS_DELETED       = TRUE,
            T.ETL_LOAD_TS      = CURRENT_TIMESTAMP(),
            T.ETL_BATCH_ID     = '${batch_id}'
        WHERE T.IS_DELETED = FALSE
          AND NOT EXISTS (
              SELECT 1 FROM ${src} S WHERE S.PART_NUMBER = T.PART_NUMBER
          )`;
        var sd_res = snowflake.execute({sqlText: soft_del_sql});
        sd_res.next();
        del_cnt = sd_res.getColumnValue(1);

        // Log SUCCESS
        var end_ts   = new Date();
        var duration = (end_ts - start_ts) / 1000;
        var log_sql  = `
        INSERT INTO ${log}
            (BATCH_ID, PROCEDURE_NAME, LOAD_TYPE, STATUS, WATERMARK_FROM, WATERMARK_TO,
             SOURCE_COUNT, INSERTED_COUNT, UPDATED_COUNT, DELETED_COUNT, EXCLUDED_COUNT,
             ERROR_MESSAGE, START_TS, END_TS, DURATION_SECONDS)
        VALUES
            ('${batch_id}','${proc_name}','${load_type}','SUCCESS',
             ${wm_from ? "'"+wm_from+"'" : 'NULL'}, '${wm_to}',
             ${src_cnt}, ${ins_cnt}, ${upd_cnt}, ${del_cnt}, ${exc_cnt},
             NULL, '${start_ts.toISOString()}', '${end_ts.toISOString()}', ${duration})`;
        snowflake.execute({sqlText: log_