/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Daily Snowflake Task to execute SCD1 aerospace parts pipeline
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
Generated On: 2026-09-11
=========================================================*/

USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- ── SUPPORTING OBJECTS ────────────────────────────────────────────────────────

-- SECTION 2: Source Processing
CREATE TABLE -- SECTION 3: Data Validation
IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE (
    PART_NUMBER        VARCHAR(100),
    PART_NAME          VARCHAR(255),
    MANUFACTURER       VARCHAR(255),
    WEIGHT_KG          NUMBER(10,4),
    UNIT_PRICE_USD     NUMBER(14,4),
    LIFECYCLE_STATUS   VARCHAR(100),
    INSTALLATION_DATE  DATE,
    CERTIFICATION      VARCHAR(100),
    LEAD_TIME_DAYS     NUMBER(6),
    UPDATED_AT         TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET (
    PART_NUMBER        VARCHAR(100)   NOT NULL PRIMARY KEY,
    PART_NAME          VARCHAR(255),
    MANUFACTURER       VARCHAR(255),
    WEIGHT_KG          NUMBER(10,4),
    UNIT_PRICE_USD     NUMBER(14,4),
    LIFECYCLE_STATUS   VARCHAR(100),
    INSTALLATION_DATE  DATE,
    CERTIFICATION      VARCHAR(100),
    LEAD_TIME_DAYS     NUMBER(6),
    RISK_SCORE         VARCHAR(20),
    IS_DELETED         BOOLEAN        DEFAULT FALSE,
    UPDATED_AT         TIMESTAMP_NTZ,
    ETL_LOAD_TS        TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
    LOG_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
    PROCEDURE_NAME     VARCHAR(200),
    RUN_START_TS       TIMESTAMP_NTZ,
    RUN_END_TS         TIMESTAMP_NTZ,
    STATUS             VARCHAR(20),
    SOURCE_COUNT       NUMBER,
    TARGET_INSERTED    NUMBER,
    TARGET_UPDATED     NUMBER,
    TARGET_DELETED     NUMBER,
    EXCLUDED_COUNT     NUMBER,
    ERROR_MESSAGE      VARCHAR(4000),
    LAST_LOAD_TS       TIMESTAMP_NTZ
);

-- ── STORED PROCEDURE ──────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
-- SECTION 1: Variables

    v_start_ts        TIMESTAMP_NTZ;
    v_last_load_ts    TIMESTAMP_NTZ;
    v_src_count       NUMBER DEFAULT 0;
    v_inserted        NUMBER DEFAULT 0;
    v_updated         NUMBER DEFAULT 0;
    v_deleted         NUMBER DEFAULT 0;
    v_excluded        NUMBER DEFAULT 0;
    v_err             VARCHAR(4000);
    v_cutoff_date     DATE;
BEGIN
    v_start_ts    := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    v_cutoff_date := DATEADD('year', -3, CURRENT_DATE());

    -- Resolve last successful load timestamp (NULL = first/full run)
    SELECT MAX(LAST_LOAD_TS)
      INTO v_last_load_ts
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
     WHERE PROCEDURE_NAME = 'SP_LOAD_AEROSPACE_PARTS_SCD1'
       AND STATUS = 'SUCCESS';

    -- ── STAGE: deduplicated + filtered source ─────────────────────────────────
    CREATE OR REPLACE TEMPORARY TABLE AEROSPACE_PARTS_STAGE AS
    WITH deduped AS (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS rn
          FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
         WHERE (v_last_load_ts IS NULL OR UPDATED_AT > v_last_load_ts)
    ),
    ranked AS (
        SELECT PART_NUMBER,
               PART_NAME,
               INITCAP(MANUFACTURER)                          AS MANUFACTURER,
               CASE WHEN WEIGHT_KG <= 0 THEN NULL
                    ELSE WEIGHT_KG END                        AS WEIGHT_KG,
               ROUND(UNIT_PRICE_USD, 2)                       AS UNIT_PRICE_USD,
               LIFECYCLE_STATUS,
               INSTALLATION_DATE,
               CERTIFICATION,
               LEAD_TIME_DAYS,
               UPDATED_AT,
               CASE
                 WHEN UPPER(CERTIFICATION) = 'PENDING'
                      AND LEAD_TIME_DAYS > 90                 THEN 'High Risk'
                 WHEN UPPER(CERTIFICATION) = 'PENDING'
                      OR  LEAD_TIME_DAYS > 120                THEN 'Medium Risk'
                 WHEN UPPER(CERTIFICATION) IN ('FAA','EASA','DUAL')
                      AND LEAD_TIME_DAYS <= 60                THEN 'Low Risk'
                 ELSE 'Medium Risk'
               END                                            AS RISK_SCORE
          FROM deduped
         WHERE rn = 1
    )
    SELECT *
      FROM ranked
     WHERE NOT (
               UPPER(LIFECYCLE_STATUS) = 'END OF LIFE'
           AND INSTALLATION_DATE < v_cutoff_date
           );

    -- Source count (post-dedup, post-exclusion)
    SELECT COUNT(*) INTO v_src_count FROM AEROSPACE_PARTS_STAGE;

    -- Excluded count
    WITH raw_deduped AS (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY UPDATED_AT DESC) AS rn
          FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
         WHERE (v_last_load_ts IS NULL OR UPDATED_AT > v_last_load_ts)
    )
    SELECT COUNT(*) INTO v_excluded
      FROM raw_deduped
     WHERE rn = 1
       AND UPPER(LIFECYCLE_STATUS) = 'END OF LIFE'
       AND INSTALLATION_DATE < v_cutoff_date;

    -- ── SCD1 MERGE ────────────────────────────────────────────────────────────
    -- SECTION 4: Merge Logic
MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET  tgt
    USING AEROSPACE_PARTS_STAGE                                             src
       ON tgt.PART_NUMBER = src.PART_NUMBER
    WHEN MATCHED THEN UPDATE SET
        tgt.PART_NAME        = src.PART_NAME,
        tgt.MANUFACTURER     = src.MANUFACTURER,
        tgt.WEIGHT_KG        = src.WEIGHT_KG,
        tgt.UNIT_PRICE_USD   = src.UNIT_PRICE_USD,
        tgt.LIFECYCLE_STATUS = src.LIFECYCLE_STATUS,
        tgt.INSTALLATION_DATE= src.INSTALLATION_DATE,
        tgt.CERTIFICATION    = src.CERTIFICATION,
        tgt.LEAD_TIME_DAYS   = src.LEAD_TIME_DAYS,
        tgt.RISK_SCORE       = src.RISK_SCORE,
        tgt.IS_DELETED       = FALSE,
        tgt.UPDATED_AT       = src.UPDATED_AT,
        tgt.ETL_LOAD_TS      = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER, PART_NAME, MANUFACTURER, WEIGHT_KG, UNIT_PRICE_USD,
        LIFECYCLE_STATUS, INSTALLATION_DATE, CERTIFICATION, LEAD_TIME_DAYS,
        RISK_SCORE, IS_DELETED, UPDATED_AT, ETL_LOAD_TS
    ) VALUES (
        src.PART_NUMBER, src.PART_NAME, src.MANUFACTURER, src.WEIGHT_KG,
        src.UNIT_PRICE_USD, src.LIFECYCLE_STATUS, src.INSTALLATION_DATE,
        src.CERTIFICATION, src.LEAD_TIME_DAYS, src.RISK_SCORE,
        FALSE, src.UPDATED_AT, CURRENT_TIMESTAMP()
    );

    -- Capture merge row counts via query_history approximation
    SELECT COUNT(*) INTO v_inserted
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET tgt
     WHERE tgt.ETL_LOAD_TS >= v_start_ts
       AND tgt.IS_DELETED = FALSE
       AND NOT EXISTS (
           SELECT 1 FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
            WHERE 1=0  -- placeholder; use CHANGES clause or audit table in production
       );

    -- Simplified insert/update split via ETL_LOAD_TS vs UPDATED_AT proximity
    SELECT COUNT(*) INTO v_inserted
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
     WHERE ETL_LOAD_TS >= v_start_ts
       AND UPDATED_AT  = ETL_LOAD_TS;   -- new rows: both stamps align on insert

    SELECT COUNT(*) INTO v_updated
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
     WHERE ETL_LOAD_TS >= v_start_ts
       AND UPDATED_AT != ETL_LOAD_TS;

    -- ── SOFT DELETE: mark records absent from full source as Decommissioned ───
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET tgt
       SET tgt.LIFECYCLE_STATUS = 'Decommissioned',
           tgt.IS_DELETED       = TRUE,
           tgt.ETL_LOAD_TS      = CURRENT_TIMESTAMP()
     WHERE tgt.IS_DELETED = FALSE
       AND v_last_load_ts IS NULL   -- only on full load pass
       AND NOT EXISTS (
           SELECT 1 FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE src
            WHERE src.PART_NUMBER = tgt.PART_NUMBER
       );

    SELECT COUNT(*) INTO v_deleted
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET
     WHERE IS_DELETED = TRUE
       AND ETL_LOAD_TS >= v_start_ts;

    -- ── RECONCILIATION LOG ────────────────────────────────────────────────────
    -- SECTION 5: Reconciliation
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
        (PROCEDURE_NAME, RUN_START_TS, RUN_END_TS, STATUS,
         SOURCE_COUNT, TARGET_INSERTED, TARGET_UPDATED, TARGET_DELETED,
         EXCLUDED_COUNT, ERROR_MESSAGE, LAST_LOAD_TS)
    VALUES
        ('SP_LOAD_AEROSPACE_PARTS_SCD1', v_start_ts, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
         'SUCCESS', v_src_count, v_inserted, v_updated, v_deleted,
         v_excluded, NULL, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ);

    RETURN 'SUCCESS | src=' || v_src_count
        || ' ins=' || v_inserted
        || ' upd=' || v_updated
        || ' del=' || v_deleted
        || ' excl=' || v_excluded;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN
        v_err := SQLERRM;
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
            (PROCEDURE_NAME, RUN_START_TS, RUN_END_TS, STATUS,
             SOURCE_COUNT, TARGET_INSERTED, TARGET_UPDATED, TARGET_DELETED,
             EXCLUDED_COUNT, ERROR_MESSAGE, LAST_LOAD_TS)
        VALUES
            ('SP_LOAD_AEROSPACE_PARTS_SCD1', v_start_ts, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
             'FAILED', 0, 0, 0, 0, 0, v_err, NULL);
        RETURN 'FAILED: ' || v_err;

$$;

-- ── TASK ──────────────────────────────────────────────────────────────────────

CREATE OR REPLACE TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    SCHEDULE  = 'USING CRON 0 2 * * * UTC'
    COMMENT   = 'Daily 02:00 UTC SCD1 load for Aerospace Parts Inventory'
AS
    CALL GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1();

ALTER TASK GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.TASK_SP_LOAD_AEROSPACE_PARTS_SCD1 RESUME;