/*=========================================================
Object Name : DDL_AEROSPACE_PARTS_TARGET
Purpose     : Target table DDL
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE GEN_AI_POC_SNOWFLAKECOE;
USE SCHEMA SDLC_WIZARD;

-- SECTION 1: Object Definition
CREATE TABLE IF NOT EXISTS AEROSPACE_PARTS_TARGET (
    PART_NUMBER          VARCHAR(50)     NOT NULL,
    MANUFACTURER         VARCHAR(100),
    WEIGHT_KG            NUMBER(10,4),
    UNIT_PRICE_USD       NUMBER(14,4),
    LIFECYCLE_STATUS     VARCHAR(50),
    CERTIFICATION_STATUS VARCHAR(50),
    LEAD_TIME_DAYS       NUMBER(6,0),
    STOCK_QUANTITY       NUMBER(12,0),
    WAREHOUSE_LOCATION   VARCHAR(100),
    SUPPLIER_CODE        VARCHAR(50),
    STATUS               VARCHAR(50)     DEFAULT 'Active',
    RISK_SCORE           VARCHAR(20),
    UPDATED_AT           TIMESTAMP_NTZ,
    CREATED_AT           TIMESTAMP_NTZ,
    DW_INSERT_DATE       TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATE_DATE       TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- SECTION 2: Constraints
ALTER TABLE AEROSPACE_PARTS_TARGET
    ADD CONSTRAINT IF NOT EXISTS PK_APT_PART_NUMBER PRIMARY KEY (PART_NUMBER);

-- SECTION 3: Notes
-- SCD Type 1: updates overwrite existing records
-- RISK_SCORE derived from CERTIFICATION_STATUS + LEAD_TIME_DAYS
-- Soft delete: STATUS = 'Decommissioned' for records absent from source
-- DW_INSERT_DATE set on first insert; DW_UPDATE_DATE refreshed on every merge