/*=========================================================
Object Name : TASK_SP_LOAD_AEROSPACE_PARTS_SCD1
Purpose     : Main pipeline stored procedure
Author      : SDLC_AGENT
Generated By: SDLC_AGENT
=========================================================*/

CREATE OR REPLACE PROCEDURE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.SP_LOAD_AEROSPACE_PARTS_SCD1()
RETURNS VARCHAR
LANGUAGE SQL
WAREHOUSE = SNOWFLAKE_LEARNING_WH
AS
$$
-- SECTION 1: Variables

    -- Run metadata
    v_pipeline_name     VARCHAR DEFAULT 'SP_LOAD_AEROSPACE_PARTS_SCD1';
    v_run_id            VARCHAR DEFAULT REPLACE(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDD_HH24MISS_FF3'), ' ', '_');
    v_run_timestamp     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP::TIMESTAMP_NTZ;

    -- Watermark tracking
    v_watermark_-- SECTION 2: Source Processing
from    TIMESTAMP_NTZ;
    v_watermark_to      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP::TIMESTAMP_NTZ;

    -- Row counters
    v_source_count      INTEGER DEFAULT 0;
    v_target_count      INTEGER DEFAULT 0;
    v_inserted_count    INTEGER DEFAULT 0;
    v_updated_count     INTEGER DEFAULT 0;
    v_deleted_count     INTEGER DEFAULT 0;
    v_execution_sec     FLOAT   DEFAULT 0;

    -- Status / error
    v_status            VARCHAR DEFAULT 'SUCCESS';
    v_error_message     VARCHAR DEFAULT NULL;

    -- Timer
    v_start_ts          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP::TIMESTAMP_NTZ;

    -- Result message
    v_result            VARCHAR;

BEGIN

    -- ----------------------------------------------------------------
    -- STEP 1: Resolve incremental watermark
    --         Use the MAX WATERMARK_TO from prior successful runs,
    --         or fall back to epoch -- SECTION 3: Data Validation
if no prior run exists.
    -- ----------------------------------------------------------------
    SELECT COALESCE(MAX(WATERMARK_TO), '1900-01-01 00:00:00'::TIMESTAMP_NTZ)
      INTO :v_watermark_from
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG
     WHERE PIPELINE_NAME = :v_pipeline_name
       AND STATUS        = 'SUCCESS';

    -- ----------------------------------------------------------------
    -- STEP 2: Count raw source rows in the incremental window
    -- ----------------------------------------------------------------
    SELECT COUNT(*)
      INTO :v_source_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
     WHERE UPDATED_AT >  :v_watermark_from
       AND UPDATED_AT <= :v_watermark_to;

    -- ----------------------------------------------------------------
    -- STEP 3: Count current target rows (pre-merge snapshot)
    -- ----------------------------------------------------------------
    SELECT COUNT(*)
      INTO :v_target_count
      FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

    -- ----------------------------------------------------------------
    -- STEP 4: Deduplicate source — keep latest record per PART_NUMBER
    --         then -- SECTION 4: Merge Logic
MERGE into target (SCD Type 1)
    -- ----------------------------------------------------------------
    MERGE INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET  AS TGT
    USING (
        -- Deduplicated source CTE: one row per PART_NUMBER, latest UPDATED_AT wins
        SELECT
            SRC.PART_NUMBER,
            SRC.MANUFACTURER,
            SRC.SUPPLIER_CODE,
            SRC.WAREHOUSE_LOCATION,
            SRC.UNIT_PRICE_USD,
            SRC.STOCK_QUANTITY,
            SRC.LEAD_TIME_DAYS,
            SRC.WEIGHT_KG,
            SRC.CERTIFICATION_STATUS,
            SRC.LIFECYCLE_STATUS,
            SRC.CREATED_AT,
            SRC.UPDATED_AT,
            -- RISK_SCORE derivation business rule:
            --   HIGH   : LIFECYCLE_STATUS = 'OBSOLETE'  OR  CERTIFICATION_STATUS = 'EXPIRED'
            --   MEDIUM : STOCK_QUANTITY < 10             OR  LEAD_TIME_DAYS > 90
            --   LOW    : all other cases
            CASE
                WHEN SRC.LIFECYCLE_STATUS      = 'OBSOLETE'
                  OR SRC.CERTIFICATION_STATUS  = 'EXPIRED'
                    THEN 'HIGH'
                WHEN SRC.STOCK_QUANTITY < 10
                  OR SRC.LEAD_TIME_DAYS > 90
                    THEN 'MEDIUM'
                ELSE 'LOW'
            END AS RISK_SCORE
        FROM (
            SELECT
                PART_NUMBER,
                MANUFACTURER,
                SUPPLIER_CODE,
                WAREHOUSE_LOCATION,
                UNIT_PRICE_USD,
                STOCK_QUANTITY,
                LEAD_TIME_DAYS,
                WEIGHT_KG,
                CERTIFICATION_STATUS,
                LIFECYCLE_STATUS,
                CREATED_AT,
                UPDATED_AT,
                ROW_NUMBER() OVER (
                    PARTITION BY PART_NUMBER
                    ORDER BY UPDATED_AT DESC
                ) AS RN
            FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE
            WHERE UPDATED_AT >  :v_watermark_from
              AND UPDATED_AT <= :v_watermark_to
        ) SRC
        WHERE SRC.RN = 1
    ) AS DEDUP_SRC
    ON TGT.PART_NUMBER = DEDUP_SRC.PART_NUMBER

    -- ----------------------------------------------------------------
    -- MATCHED  →  SCD Type 1 overwrite (UPDATE)
    -- ----------------------------------------------------------------
    WHEN MATCHED THEN UPDATE SET
        TGT.MANUFACTURER         = DEDUP_SRC.MANUFACTURER,
        TGT.SUPPLIER_CODE        = DEDUP_SRC.SUPPLIER_CODE,
        TGT.WAREHOUSE_LOCATION   = DEDUP_SRC.WAREHOUSE_LOCATION,
        TGT.UNIT_PRICE_USD       = DEDUP_SRC.UNIT_PRICE_USD,
        TGT.STOCK_QUANTITY       = DEDUP_SRC.STOCK_QUANTITY,
        TGT.LEAD_TIME_DAYS       = DEDUP_SRC.LEAD_TIME_DAYS,
        TGT.WEIGHT_KG            = DEDUP_SRC.WEIGHT_KG,
        TGT.CERTIFICATION_STATUS = DEDUP_SRC.CERTIFICATION_STATUS,
        TGT.LIFECYCLE_STATUS     = DEDUP_SRC.LIFECYCLE_STATUS,
        TGT.CREATED_AT           = DEDUP_SRC.CREATED_AT,
        TGT.UPDATED_AT           = DEDUP_SRC.UPDATED_AT,
        TGT.RISK_SCORE           = DEDUP_SRC.RISK_SCORE,
        TGT.STATUS               = 'ACTIVE',
        TGT.DW_UPDATE_DATE       = CURRENT_TIMESTAMP::TIMESTAMP_NTZ

    -- ----------------------------------------------------------------
    -- NOT MATCHED  →  INSERT new record
    -- ----------------------------------------------------------------
    WHEN NOT MATCHED THEN INSERT (
        PART_NUMBER,
        MANUFACTURER,
        SUPPLIER_CODE,
        WAREHOUSE_LOCATION,
        UNIT_PRICE_USD,
        STOCK_QUANTITY,
        LEAD_TIME_DAYS,
        WEIGHT_KG,
        CERTIFICATION_STATUS,
        LIFECYCLE_STATUS,
        CREATED_AT,
        UPDATED_AT,
        RISK_SCORE,
        STATUS,
        DW_INSERT_DATE,
        DW_UPDATE_DATE
    ) VALUES (
        DEDUP_SRC.PART_NUMBER,
        DEDUP_SRC.MANUFACTURER,
        DEDUP_SRC.SUPPLIER_CODE,
        DEDUP_SRC.WAREHOUSE_LOCATION,
        DEDUP_SRC.UNIT_PRICE_USD,
        DEDUP_SRC.STOCK_QUANTITY,
        DEDUP_SRC.LEAD_TIME_DAYS,
        DEDUP_SRC.WEIGHT_KG,
        DEDUP_SRC.CERTIFICATION_STATUS,
        DEDUP_SRC.LIFECYCLE_STATUS,
        DEDUP_SRC.CREATED_AT,
        DEDUP_SRC.UPDATED_AT,
        DEDUP_SRC.RISK_SCORE,
        'ACTIVE',
        CURRENT_TIMESTAMP::TIMESTAMP_NTZ,
        CURRENT_TIMESTAMP::TIMESTAMP_NTZ
    );

    -- ----------------------------------------------------------------
    -- STEP 5: Capture MERGE row counts from query profile metadata
    -- ----------------------------------------------------------------
    v_inserted_count := SQLROWCOUNT;   -- rows affected by last DML

    -- Re-derive inserted vs updated by comparing target counts
    -- (Snowflake SQLROWCOUNT reflects total rows touched by MERGE)
    -- Use post-merge target count delta for inserted; remainder = updated
    DECLARE
        v_target_count_after INTEGER DEFAULT 0;
    BEGIN
        SELECT COUNT(*)
          INTO :v_target_count_after
          FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET;

        v_inserted_count := v_target_count_after - v_target_count;
        v_updated_count  := SQLROWCOUNT - v_inserted_count;

        -- Guard against negative values from edge cases
        IF (v_updated_count < 0) THEN
            v_updated_count := 0;
        END IF;
    END;

    -- ----------------------------------------------------------------
    -- STEP 6: Soft-delete — mark target records INACTIVE when their
    --         PART_NUMBER no longer appears in the full source table
    -- ----------------------------------------------------------------
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_TARGET AS TGT
       SET TGT.STATUS         = 'INACTIVE',
           TGT.DW_UPDATE_DATE = CURRENT_TIMESTAMP::TIMESTAMP_NTZ
     WHERE TGT.STATUS = 'ACTIVE'
       AND NOT EXISTS (
               SELECT 1
                 FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.AEROSPACE_PARTS_SOURCE SRC
                WHERE SRC.PART_NUMBER = TGT.PART_NUMBER
           );

    v_deleted_count := SQLROWCOUNT;

    -- ----------------------------------------------------------------
    -- STEP 7: Calculate execution duration
    -- ----------------------------------------------------------------
    v_execution_sec := DATEDIFF('millisecond', :v_start_ts, CURRENT_TIMESTAMP::TIMESTAMP_NTZ) / 1000.0;

    -- ----------------------------------------------------------------
    -- STEP 8: Log SUCCESS run to ETL_RECONCILIATION_LOG
    -- ----------------------------------------------------------------
    -- SECTION 5: Reconciliation
INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
        RUN_ID,
        PIPELINE_NAME,
        RUN_TIMESTAMP,
        SOURCE_COUNT,
        TARGET_COUNT,
        INSERTED_COUNT,
        UPDATED_COUNT,
        DELETED_COUNT,
        EXECUTION_SEC,
        WATERMARK_FROM,
        WATERMARK_TO,
        STATUS,
        ERROR_MESSAGE
    ) VALUES (
        :v_run_id,
        :v_pipeline_name,
        :v_run_timestamp,
        :v_source_count,
        :v_target_count,
        :v_inserted_count,
        :v_updated_count,
        :v_deleted_count,
        :v_execution_sec,
        :v_watermark_from,
        :v_watermark_to,
        :v_status,
        :v_error_message
    );

    -- ----------------------------------------------------------------
    -- STEP 9: Build and return success summary
    -- ----------------------------------------------------------------
    v_result := OBJECT_CONSTRUCT(
        'status',          :v_status,
        'pipeline_name',   :v_pipeline_name,
        'run_id',          :v_run_id,
        'run_timestamp',   TO_VARCHAR(:v_run_timestamp),
        'watermark_from',  TO_VARCHAR(:v_watermark_from),
        'watermark_to',    TO_VARCHAR(:v_watermark_to),
        'source_count',    :v_source_count,
        'target_count',    :v_target_count,
        'inserted_count',  :v_inserted_count,
        'updated_count',   :v_updated_count,
        'deleted_count',   :v_deleted_count,
        'execution_sec',   :v_execution_sec
    )::VARCHAR;

    RETURN v_result;

-- SECTION 6: Error Handling
EXCEPTION
    WHEN OTHER THEN

        v_status        := 'FAILED';
        v_error_message := SQLERRM;
        v_execution_sec := DATEDIFF('millisecond', :v_start_ts, CURRENT_TIMESTAMP::TIMESTAMP_NTZ) / 1000.0;

        -- Log FAILED run — wrapped in its own BEGIN/END to isolate
        -- any secondary failure from masking the original error
        BEGIN
            INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ETL_RECONCILIATION_LOG (
                RUN_ID,
                PIPELINE_NAME,
                RUN_TIMESTAMP,
                SOURCE_COUNT,
                TARGET_COUNT,
                INSERTED_COUNT,
                UPDATED_COUNT,
                DELETED_COUNT,
                EXECUTION_SEC,
                WATERMARK_FROM,
                WATERMARK_TO,
                STATUS,
                ERROR_MESSAGE
            ) VALUES (
                :v_run_id,
                :v_pipeline_name,
                :v_run_timestamp,
                :v_source_count,
                :v_target_count,
                :v_inserted_count,
                :v_updated_count,
                :v_deleted_count,
                :v_execution_sec,
                :v_watermark_from,
                :v_watermark_to,
                :v_status,
                :v_error_message
            );
        EXCEPTION
            WHEN OTHER THEN
                NULL;   -- Suppress secondary logging failure; surface original error below
        END;

        RETURN OBJECT_CONSTRUCT(
            'status',        'FAILED',
            'pipeline_name', :v_pipeline_name,
            'run_id',        :v_run_id,
            'error',         :v_error_message
        )::VARCHAR;

END;
$$;